name: spott

description: A new Flutter project.

publish_to: none

#version: 1.0.0+1

dependencies:
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  camera: ^0.9.2+2
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  dio: ^4.0.0
  dots_indicator: ^2.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  flutter_geocoder: ^0.2.2-nullsafety
  flutter_svg: ^0.22.0
  geolocator: ^7.6.0
  get_storage: ^2.0.3
  google_sign_in: ^5.0.1
  image_picker: ^0.8.4
  intl: ^0.17.0
  timeago: ^3.1.0
  onesignal_flutter: ^3.2.4
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.10
  video_player: ^2.1.15
  easy_localization: ^3.0.0
  app_settings: ^4.1.1
  uni_links: ^0.5.1
  share: ^2.0.4
  cloud_firestore: ^2.5.2
  firebase_core: ^1.6.0
  google_fonts:
  firebase_storage: ^10.0.3
  flutter_sound_lite: ^8.3.12
  audioplayers: ^0.20.1
  flutter_rating_bar: ^4.0.0
  googleapis: ^5.0.1
  http: ^0.13.3
  location: ^4.3.0
  flutter_reaction_button: ^1.0.8
  socket_io_client: ^0.9.12
  sizer: ^2.0.15


  story_view:
    path: ./packages/stories
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
#  lint: ^1.7.2
environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/reactions/
  uses-material-design: true

  fonts:
    - family: SFUI
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf

flutter_icons:
  android: launcher_icon
  image_path: assets/images/app_icon.png
  ios: true
