include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_final_locals: false
    type_annotate_public_apis: false
    prefer_constructors_over_static_methods: false
    prefer_const_constructors: false
    always_declare_return_types: false
    sort_child_properties_last: false
    prefer_if_null_operators: false
    avoid_unused_constructor_parameters: false
    prefer_const_constructors_in_immutables: false
    prefer_is_empty: false
    avoid_function_literals_in_foreach_calls: false
    unnecessary_this: false
    prefer_conditional_assignment: false
    avoid_positional_boolean_parameters: false
    argument_type_not_assignable: false
    directives_ordering: false
    prefer_is_not_operator: false
    avoid_void_async: false
    avoid_redundant_argument_values: false
    sized_box_for_whitespace: false
    invalid_assignment: false
    sort_pub_dependencies: false
    use_setters_to_change_properties: false
    