---
dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  rxdart: ^0.27.1
  video_player: ^2.1.14
description: Display stories just like Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter: null
homepage: https://github.com/blackmann/story_view
name: story_view
version: 0.13.1